[package]
name = "scoundrel"
version = "0.1.0"
edition = "2021"

[dependencies]
scoundrel-algorithm = { path = "../scoundrel-algorithm" }
scoundrel-geometry = { path = "../scoundrel-geometry" }
scoundrel-util = { path = "../scoundrel-util" }
scoundrel-procedural = { optional = true, path = "../scoundrel-procedural" }
scoundrel-ui = { path = "../scoundrel-ui", optional = true }
thiserror = "1.0"
tui = { version = "0.16", optional = true, default-features = false, features = ["crossterm"] }

wgpu = { version = "0.12", optional = true }
naga = { version = "0.8", optional = true, features = ["wgsl-in", "validate", "codespan-reporting"] }
pollster = { version = "0.2.4", optional = true }

[features]
serde = ["scoundrel-geometry/serde"]
ui = ["scoundrel-ui", "scoundrel-geometry/tui", "tui"]
gpu = [ "wgpu", "naga", "pollster", "scoundrel-procedural" ]
