[package]
name = "scoundrel-util"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0"
serde = { version = "1.0", optional = true }
serde_json = { version = "1.0", optional = true }

[features]
_serde = ["serde", "serde_json"]
