[package]
name = "scoundrel-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.52"
tui = { version = "0.16.0", default-features = false, features = ["crossterm"] }
serde = { version = "1.0", features = ["derive"] }
scoundrel-geometry = { path = "../scoundrel-geometry" }
